name: "JFrog-GitHub Docker Publish OIDC Integration"
on: push

# This is required as person123456789
# https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-cloud-providers#adding-permissions-settings
permissions:
  id-token: write
  contents: read 

jobs:
  build:
     runs-on: [self-hosted, k8s-app-deploy]
     container:
      image: incloudmaster.jfrog.io/docker-remote/node:lts-alpine
      credentials:
        username: ${{ secrets.JFROG_USER }}
        password: ${{ secrets.JFROG_ACCESS_TOKEN }}
        
     steps:
       - name: Logs
         run: |
          printenv

       - name: Setup JFrog CLI
         uses: jfrog/setup-jfrog-cli@v4
         env:  
           JF_URL: ${{ secrets.JF_URL }}
         with:
           oidc-provider-name: san-git-intergation
           oidc-audience: jfrog-github
           
