name: "JFrog-GitHub NPM Publish OIDC Integration"
on: push

# This is required as per
# https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-cloud-providers#adding-permissions-settings
permissions:
  id-token: write
env:
  OIDC_AUDIENCE: 'jfrog-github'
  PLATFORM_REPO: 'ashritha-npm-npm'
jobs:
  deploy:
    name: JCA OIDC Generic Push Simple
    runs-on: [self-hosted, elastic, linux, default]

    steps:
      - name: Generate 1MB File
        run: |
          head -c 1MB </dev/urandom >dummy
          ls -alih dummy
          
      - name: Setup JFrog CLI With OIDC
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ secrets.JF_URL }}
        with:
           oidc-provider-name: san-git-intergation
           oidc-audience: jfrog-github

      - name: Push Generic Artifact
        env:
          ACCESS_TOKEN: ${{ env.ACCESS_TOKEN}}
        run: |
          ls -lart
          jf rt upload --url ${{ secrets.JF_URL }}/artifactory dummy $PLATFORM_REPO
